[project]
name = "ranlib"
version = "0.1.0"
description = "Add a short description here"
authors = [
  "Anemo AI <anemo@anemo.ai>",
  "Ameer Arsala <ameer@anemo.ai>",
  "Ishan Meher <sean@anemo.ai>",
]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.9.*"
pydantic = ">=2.0"
python-dotenv = ">=1.0.1,<1.1"

[pypi-dependencies]
tomli = ">=2.0.1, <2.1"
tomli-w = ">=1.0.0, <1.1"
pyyaml = ">=6.0.1, <6.1"
typer = ">=0.12.3, <0.13"
rich = ">=13.7.1, <13.8"
gitpython = ">=3.1.43, <3.2"
pytest = ">=8.2.2, <8.3"
pre-commit = ">=3.7.1, <3.8"
