[project]
name = "ranlib"
version = "0.1.0"
description = "Add a short description here"
authors = ["ShanMehr <ishanmeher25@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
ran = "python ./ranlib/main.py"

[dependencies]
pydantic = ">=2.8.2,<2.9"
pytest = ">=8.2.2,<8.3"
typer = ">=0.12.3,<0.13"
python-dotenv = ">=1.0.1,<1.1"
pre-commit = ">=3.7.1,<3.8"
tomli = ">=2.0.1,<2.1"
tomli-w = ">=1.0.0,<1.1"
pyyaml = ">=6.0.1,<6.1"
rich = ">=13.7.1,<13.8"
gitpython = ">=3.1.43,<3.2"
requests = ">=2.32.3,<2.33"
